@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60

actor User
participant "ProductController" as A
participant "ProductServiceImpl" as B
participant "ProductDAOImpl" as C
database "MySQL_DB" as D

User -> A: index
activate A

A -> B: addCartDetail()
activate B
activate D

B -> C: getById()
activate C
C -> D: search
D --> C: result


C --> B: Products



B -> C: getCartByUserId()
activate C
C -> D: search
D --> C: result

C --> B: cart



B --> A: void()
deactivate B

A --> User: redirect:/showProducts



@enduml
