@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60

actor User
participant "ProductController" as A
participant "ProductServiceImpl" as B
participant "ProductDAOImpl" as C
database "MySQL_DB" as D

User -> A: processForm
activate A

A -> B: getAll()()
activate B

B -> C: getAll()()
activate C
C -> D: search
D --> C: result


C --> B: List<Products>
deactivate C

B --> A: List<Products>
deactivate B

A --> User: /showProducts

deactivate A


@enduml
